[package]
name = "sqlite_nostd"
version = "0.1.0"
edition = "2021"
authors = ["Matt Wonlaw"]
description = "Minimal bindings for SQLite3 that do not require std"
keywords = ["sqlite"]
license = "MIT"

[dependencies]
sqlite3_capi = {version="0.1.0", path="./sqlite3_capi"}

